on:
  push:
    branches:
      - main
jobs:
  update-prod-form:
    runs-on: ubuntu-latest
    name: 'Update PROD Power Apps form'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update
        uses: ./
